name: 🐛 Bug Report
description: ForinK 서비스에서 발생한 문제를 기록하고 해결해요.
title: '[Bug] 🐛 요약을 작성해주세요'
labels: ['bug', 'needs triage']
body:
  - type: textarea
    id: description
    attributes:
      label: 🧩 어떤 문제가 있었나요?
      placeholder: 어떤 상황에서 어떤 문제가 발생했는지 자세히 알려주세요.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔁 재현 방법
      placeholder: |
        1. 어떤 페이지/상황에서
        2. 어떤 행동을 했고
        3. 어떤 결과가 나왔는지
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ 기대 동작
      placeholder: 예상했거나 정상적으로 보여야 할 동작은 무엇인가요?
    validations:
      required: false

  - type: textarea
    id: env
    attributes:
      label: 🧪 테스트 환경
      placeholder: 브라우저, 기기, OS, 테스트 계정 등
    validations:
      required: false
